---
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: "5s"
          static_configs:
            - targets: ["spicedb:9090"]

processors:
  # TODO: filter
  batch:
  memory_limiter:
    check_interval: 5s
    limit_mib: 4000
    spike_limit_mib: 500

exporters:
  prometheus:
    endpoint: "0.0.0.0:9090"
    enable_open_metrics: true

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [memory_limiter, batch]
      exporters: [prometheus]
